export enum Action {
    Delete = "delete",
    Update = "update",
    Get = "get",
    Custom = "custom",
    Copy = "copy",
};
export const AcceptFileList = {
    allFiles: '*',
    audio: '.3g2,.3gp,.aac,.adt,.adts,.aif,.aifc,.aiff,.asf,.au,.m3u,.m4a,.m4b,.mid,.midi,.mp2,.mp3,.mp4,.rmi,.snd,.wav,.wax,.wma',
    csv: '.csv',
    doc: '.doc',
    docx: '.docx',
    images: '.jpeg,.jpg,.png',
    pdf: '.pdf',
    plainText: '.txt',
    ppt: '.ppt',
    pptx: '.pptx',
    video: '.mp4',
    xls: '.xls',
    xlsx: '.xlsx',
    zip: '.zip,.gz',
    folder: 'folder',
}
export enum Status {
    GroupNumber = 1002,
    Active = 1002001,
    Passive = 1002002,
}
export enum  ComponentType {
    Date = "date",
    NullableDate = "date?",
    Select = "select",
    SelectCascade = "selectCascade",
    Input = "input",
    InputNumber = "number",
    NullabeInputNumber = "number?",
    DatePicker = "datePicker",
    Checkbox = "checkbox",
    Multiselect = "multiselect",
    Tags = "tags",
    TextArea = "textArea",
    SelectTree = "selectTree",
    SelectTreeCascade = "selectTreeCascade",
    CropImage = "cropImage",
    Editor = "editor",
    ColorEditor = "colorEditor",
    Document = "document",
    Transfer="transfer",
    Option="option",
    AutoComplete = "autoComplete",
    AutoCompleteMultiSelect = "autoCompleteMultiSelect",
    Contact = "contact",
    Mention = "mention",
    AuthorizationCode = "authorizationCode",
    ProgressBar = "progressBar",
    Numerator = "numerator",
    AddressSelect = "addressSelect",
    ContactSelect = "contactSelect",
    Formula= "formula",
    Barcode="barcode"
};